My-Puddle/my_puddle/items/urls.py
from django.urls import path
from items.views import details

app_name = 'item'
urlpatterns = [
    path('<int:pk>/', details, name='details'),
]

My-Puddle/my_puddle/my_puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index, contact, redirect_me
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('admin/', admin.site.urls),
    path('items/', include('items.urls')),
    path('redirect_me/', redirect_me, name='redirect_me'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My-Puddle/my_puddle/items/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=70)
    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=70)
    price = models.FloatField()
    is_solde = models.BooleanField(null=False)
    image = models.ImageField(upload_to='media')
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

My-Puddle/my_puddle/core/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from items.models import Item, Category

# Create your views here.
def index(request):
    items = Item.objects.filter(is_solde=False)[0:6]
    categorais = Category.objects.all()
    if items:
        return render(request, 'core/index.html', {
            'items': items,
            'categorais': categorais,
        })
    return render(request, 'core/no_items.html', {'message': 'No items found.'})

def contact(request):
    return render(request, 'core/contact.html')

def redirect_me(request):
    return reverse('contact')

My-Puddle/my_puddle/items/views.py
from django.shortcuts import render, get_object_or_404
from .models import Item

# Create your views here.

def details(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_solde=False).exclude(pk=pk)[0:3]
    return render(request, "item/details.html", {
        "item": item,
        "related_items": related_items,
    })

My-Puddle/my_puddle/core/templates/core/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %} | My Puddle</title>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="#" class="text-xl font-semibold">My Puddle</a>
            <div class="space-x-6">
                <a href="#" class="text-lg font-semibold hover:text-gray-500">New item</a>
                <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
            </div>
        </nav>
        <div>
            {% block content %}
            {% endblock %}
        </div>
        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>
                <p class="text-lg text-gray-500">This is my first try of doing this by myself</p>
            </div>
            <div class="w-1/3 ">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
                <ul>
                    <li>
                        <a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a>
                    </li>
                    <li>
                        <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Contact</a>
                    </li>
                    <li>
                        <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a>
                    </li>
                    <li>
                        <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a>
                    </li>
                </ul> 
            </div>
        </footer>
    </body>
</html>

My-Puddle/my_puddle/core/templates/core/contact.html
{% extends 'core/base.html' %}
{% block title %}
    Contact
{% endblock %}
{% block content %}
    <h1>contact page</h1>
{% endblock %}

My-Puddle/my_puddle/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}
    Welcome
{% endblock %}
{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest Players</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
            <div>
                <a href="{% url 'item:details' item.pk %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Teams</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for category in categorais %}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-500">{{ category.items.count }} Players</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

My-Puddle/my_puddle/core/templates/core/no_items.html
{% extends 'core/base.html' %}
{% block title %}
    No Items Found
{% endblock %}
{% block content %}
    <h1>{{ message }}</h1>
{% endblock %}

My-Puddle/my_puddle/items/templates/item/details.html
{% extends 'core/base.html' %}
{% block title %}
    {{ item.name }}
{% endblock %}
{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3">
            <img src="{{ item.image.url }}" class="rounded-xl">
        </div>
        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
            <p class="text-gray-500">
                <strong>Price:</strong>
                {{ item.price }}
            </p>
            <p class="text-gray-500">
                <strong>Seller:</strong>
                {{ item.created_by }}
            </p>
            {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong>
                <br>
                {{ item.description }}
            </p>
            {% endif %}
            <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Contact seller</a>
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Related_items items</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in related_items %}
            <div>
                <a href="{% url 'item:details' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-xl">
                    </div>
                    <div class="p-6 bg-white rounded-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Price: {{item.price}}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}